/**
 * Created by mathi on 06/03/2018.
 */

createSections();

function createSections() {

    let counter = document.querySelectorAll('h1').length;

    while (counter > 0) {

        // A section is a part of document that begins with a H1 and ends at the next H1
        // So we iterate through the DOM to create those sections
        // There's an exception : there's a kind of

        let bodyTags = document.querySelectorAll('body > h1, body > h2, body > h3, body > h4, body > h5, body > h6, body > p, body > blockquote, body > figure, body > ul, #refs');
        let newSection = document.createElement('section');

        for (let i=0; i<bodyTags.length; i++) {
            if (bodyTags[i].tagName !== 'H1' || i === 0 || bodyTags[i].id === 'refs') { // the first element always go inside the section, because it's usually a h1
                newSection.appendChild(bodyTags[i]);
            } else {
                break;
            }
        }

        document.body.appendChild(newSection);

        counter--;

    }

    giveIdToSections();

    function giveIdToSections() {

        let sections =  document.querySelectorAll('section:not(.footnotes)');

        for (let i=0; i<sections.length; i++) {
            if (sections[i].firstChild.textContent !== '') {
                let sectionId = sections[i].firstChild.textContent; // take the textcontent of the first element, that is supposed to be a h1
                sectionId = formatString(sectionId);
                sections[i].setAttribute('id', 'chap-' + sectionId); // we add a 'chap-' before, to be sure it's different from the id generated by pandoc
                // console.log("sectionId " + sectionId);
            } else {
                let letters = new RegExp(/([a-z])/, 'gi');
                for (let j=1; j<sections[i].childNodes.length; i++) {
                    if (letters.test(sections[i].childNodes[j].textContent)) { // we check if the first tag contains a text
                        let sectionId = sections[i].childNodes[j].textContent;
                        sectionId = formatString(sectionId);
                        sections[i].setAttribute('id', 'chap-' + sectionId);
                        break;
                    }
                }
            }

        }

        function formatString(stringToFormat) {

            stringToFormat = stringToFormat.replace(/([,.:'"|#=><+’…])/g,""); // remove the punctuation
            stringToFormat = stringToFormat.replace(/\s/g, '-'); // replace spaces with -

            return stringToFormat;

        }

    }

}